# Generated by Django 4.1.7 on 2023-06-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('ONeg', models.IntegerField(blank=True, null=True)),
                ('OPos', models.IntegerField(blank=True, null=True)),
                ('ANeg', models.IntegerField(blank=True, null=True)),
                ('APos', models.IntegerField(blank=True, null=True)),
                ('BNeg', models.IntegerField(blank=True, null=True)),
                ('BPos', models.IntegerField(blank=True, null=True)),
                ('ABNeg', models.IntegerField(blank=True, null=True)),
                ('ABPos', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
