# Generated by Django 4.1.7 on 2023-06-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0002_blooddb'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('BloodGroup', models.CharField(blank=True, max_length=100, null=True)),
                ('BloodUnits', models.IntegerField(blank=True, null=True)),
                ('Date', models.IntegerField(blank=True, null=True)),
                ('ContactNumber', models.IntegerField(blank=True, null=True)),
                ('Reason', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
