# Generated by Django 4.1.7 on 2023-06-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0003_requestbd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbd',
            name='Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
