# Generated by Django 4.1.7 on 2023-06-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0004_alter_requestbd_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestbd',
            name='Age',
        ),
        migrations.AddField(
            model_name='requestbd',
            name='Bystander',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestbd',
            name='Place',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
