# Generated by Django 3.2.10 on 2023-07-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0005_remove_requestbd_age_requestbd_bystander_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(blank=True, max_length=200, null=True)),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('BloodGroup', models.CharField(blank=True, max_length=200, null=True)),
                ('Password', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
