# Generated by Django 3.2.10 on 2023-07-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0006_registerdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbd',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
