# Generated by Django 3.2.10 on 2023-07-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0008_auto_20230711_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(blank=True, max_length=200, null=True)),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('LastName', models.CharField(blank=True, max_length=200, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('District', models.CharField(blank=True, max_length=200, null=True)),
                ('Place', models.CharField(blank=True, max_length=200, null=True)),
                ('Gender', models.CharField(blank=True, max_length=200, null=True)),
                ('BloodGroup', models.CharField(blank=True, max_length=200, null=True)),
                ('MobileNumber', models.IntegerField(blank=True, null=True)),
                ('BloodBank', models.CharField(blank=True, max_length=200, null=True)),
                ('Diseases', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
