# Generated by Django 3.2.10 on 2023-07-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0009_blooddonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldRequestBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Bystander', models.CharField(blank=True, max_length=100, null=True)),
                ('BloodGroup', models.CharField(blank=True, max_length=100, null=True)),
                ('BloodUnits', models.IntegerField(blank=True, null=True)),
                ('Date', models.CharField(blank=True, max_length=100, null=True)),
                ('ContactNumber', models.IntegerField(blank=True, null=True)),
                ('Place', models.CharField(blank=True, max_length=300, null=True)),
                ('Reason', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
