# Generated by Django 3.2.10 on 2023-07-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0010_oldrequestbd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oldrequestbd',
            old_name='BloodUnits',
            new_name='Hospital',
        ),
        migrations.RenameField(
            model_name='requestbd',
            old_name='BloodUnits',
            new_name='Hospital',
        ),
        migrations.AddField(
            model_name='oldrequestbd',
            name='District',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='requestbd',
            name='District',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
