# Generated by Django 3.2.10 on 2023-07-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0012_alter_requestbd_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldrequestbd',
            name='Hospital',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
