# Generated by Django 3.2.10 on 2023-07-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0013_alter_oldrequestbd_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdminName', models.CharField(blank=True, max_length=1000, null=True)),
                ('Action', models.CharField(blank=True, max_length=100, null=True)),
                ('DB', models.CharField(blank=True, max_length=100, null=True)),
                ('Time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
