# Generated by Django 3.2.10 on 2023-07-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0014_adminactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivity',
            name='Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
