# Generated by Django 3.2.10 on 2023-07-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0015_alter_adminactivity_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonation',
            name='Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldrequestbd',
            name='Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registerdb',
            name='Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestbd',
            name='Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
