# Generated by Django 3.2.10 on 2023-07-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0016_auto_20230725_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Action', models.CharField(blank=True, max_length=100, null=True)),
                ('Time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
