# Generated by Django 3.2.10 on 2023-07-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0017_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='HospitalImage'),
        ),
        migrations.AddField(
            model_name='blooddb',
            name='Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
