# Generated by Django 3.2.10 on 2023-08-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0018_auto_20230726_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Subject', models.CharField(blank=True, max_length=100, null=True)),
                ('Cv', models.ImageField(upload_to='Cv')),
                ('Message', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
