# Generated by Django 3.2.10 on 2023-08-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0019_volunteerdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=1000, null=True)),
                ('Text', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
