# Generated by Django 3.2.10 on 2023-08-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0020_faqdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=1000, null=True)),
                ('Author', models.CharField(blank=True, max_length=100, null=True)),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(upload_to='ArticleImage')),
                ('Paragraph1', models.CharField(blank=True, max_length=5000, null=True)),
                ('Paragraph2', models.CharField(blank=True, max_length=5000, null=True)),
                ('Paragraph3', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
