# Generated by Django 3.2.10 on 2023-08-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0021_articledb'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledb',
            name='Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
