# Generated by Django 3.2.10 on 2023-08-21 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0023_contactdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminactivity',
            name='DB',
        ),
    ]
