# Generated by Django 3.2.10 on 2023-08-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0024_remove_adminactivity_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Idd', models.CharField(blank=True, max_length=200, null=True)),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Comment', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
