# Generated by Django 3.2.10 on 2023-08-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0025_commentdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Question', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
