# Generated by Django 3.2.10 on 2023-08-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0026_questiondb'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondb',
            name='Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
