from django.urls import path
from web import views

urlpatterns =[
    path('', views.index, name="index"),
    path('check/', views.check, name="check"),
    path('volunteer/', views.volunteer, name="volunteer"),
    path('register/', views.register, name="register"),
    path('login', views.loginpage, name="loginpage"),
    path('contact/', views.contact, name="contact"),
    path('about/', views.about, name="about"),
    path('faq/', views.faq, name="faq"),
    path('articles/', views.news, name="news"),
    path('donations/', views.donations, name="donations"),
    path('request/', views.request, name="request"),
    path('donate/', views.donate, name="donate"),
    path('saveregister/', views.saveregister, name="saveregister"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('blooddonate/', views.blooddonate, name="blooddonate"),
    path('profile/', views.profile, name="profile"),
    path('profileedit/<int:dataid>/', views.profileedit, name="profileedit"),
    path('deleteandsave/<int:dataid>/', views.deleteandsave, name="deleteandsave"),
    path('savedonations/', views.savedonations, name="savedonations"),
    path('savevolunteer/', views.savevolunteer, name="savevolunteer"),
    path('singlearticle/<int:dataid>/', views.singlearticle, name="singlearticle"),
    path('savecontact/', views.savecontact, name="savecontact"),
    path('savecomment/', views.savecomment, name="savecomment"),
    path('addarticles/', views.addarticles, name="addarticles"),
    path('savearticlebyuser/', views.savearticlebyuser, name="savearticlebyuser"),
    path('community/', views.community, name="community"),
    path('question/<int:dataid>/', views.singlequestion, name="question"),
    path('savequestion/', views.savequestion, name="savequestion"),
    path('savequestioncomment/', views.savequestioncomment, name="savequestioncomment"),
    path('requestchat/<int:dataid>/', views.requestchat, name="requestchat"),
    path('saverequestcomment/', views.saverequestcomment, name="saverequestcomment"),

    path('testing/', views.testing, name="testing"),
]